version: 2

preset:
  image: gantry-admin://images/layouts/default.png

layout:
  /header/:
    - [logo 20, menu 80]
    - position-header

  /container-main/:
    - showcase 75:
        - [position-showcase-1 50, position-showcase-2 50]
      feature:
        - [position-feature-1 50, position-feature-2 50]
      main:
        - system-messages
        - system-content
      bottom:
        - position-bottom

    - sidebar 25:
      - social
      - position-sidebar
      - position-right

  /footer/:
    - position-footer
    - [date 25, copyright 50, branding 25]

  offcanvas:
    - particle-mobile-menu
